name: Deploy Site Reusable
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  code-analysis:
    uses: pied-piper-inc/workflows/.github/workflows/code-analysis.yml@main
    with:
      languages: 'javascript'
      
  build-deploy:
    name: Deploy App
    uses: ./.github/workflows/shared-build-deploy.yaml
    with:
      app-name: popular-repos-ghu
      app-resource-group: pied-piper-inc
    secrets: inherit
